### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by anthonytison** [kirill3333/react-avatar#72]
Hi,

I develop on Typescript (React Hooks) and when i load a page with the Avatar component i get the following issue 

`ReferenceError: self is not defined` 

and the error seems coming from node_modules/react-avatar-edit/lib/react-avatar.js:2:250

**Comment by ImStayingAlive** [comment]
If you are using SSR make sure to disable it. 

For example: I was using NextJS and I had to Load in the component with SSR disabled: 

const AvatarNoSSR = dynamic(
    () => import("react-avatar-edit"),
    {ssr: false}
)

instead of

import Avatar from 'react-avatar-edit'

Then you can use <AvatarNoSSR /> to render the compont client side.

Let me know if you need anymore help!
